/**
 * Vystra Launcher — public review source
 * Copyright (c) 2026 Stefan Reibnegger (Vystra)
 * Author: Stefan Reibnegger
 * License: Polyform Noncommercial 1.0.0 — commercial use is forbidden.
 * Official binaries: https://github.com/Stefan2010byte/viscode-launcher
 * This copy has Vystra server APIs and the Vystra shop backend removed.
 */
const {
  contextBridge,
  ipcRenderer
} = require("electron");
contextBridge.exposeInMainWorld("viscode", {
  scanPlatforms: () => ipcRenderer.invoke("platforms:scan"),
  pickGameFolder: () => ipcRenderer.invoke("manual:pick-folder"),
  hideManualGame: _0x3c3212 => ipcRenderer.invoke("manual:hide", _0x3c3212),
  setGameMeta: _0x59e0b3 => ipcRenderer.invoke("manual:set-meta", _0x59e0b3),
  resetGameMeta: _0x1e48d8 => ipcRenderer.invoke("manual:reset-meta", _0x1e48d8),
  pickGameImage: () => ipcRenderer.invoke("manual:pick-image"),
  connectPlatform: _0x507336 => ipcRenderer.invoke("platform:connect", _0x507336),
  getBanner: _0x410ea4 => ipcRenderer.invoke("banner:get", _0x410ea4),
  saveBanner: _0x2695b1 => ipcRenderer.invoke("banner:save", _0x2695b1),
  clearBanner: _0x42d1c9 => ipcRenderer.invoke("banner:clear", _0x42d1c9),
  fluxBanner: _0xf5b67c => ipcRenderer.invoke("banner:flux", _0xf5b67c),
  bannerPrompt: _0x2ed19c => ipcRenderer.invoke("banner:prompt", _0x2ed19c),
  konsoleErkennen: _0xkeArg => ipcRenderer.invoke("konsole:erkennen", _0xkeArg),
  getHardware: () => ipcRenderer.invoke("hardware:get"),
  steamLibraries: () => ipcRenderer.invoke("steam:libraries"),
  steamInstallProgress: _0xb894a5 => ipcRenderer.invoke("steam:install-progress", _0xb894a5),
  steamOwned: () => ipcRenderer.invoke("steam:owned"),
  steamAccounts: () => ipcRenderer.invoke("steam:accounts"),
  steamOwnedMulti: () => ipcRenderer.invoke("steam:owned-multi"),
  steamLaunchAs: (_0x789479, _0x3cb95d) => ipcRenderer.invoke("steam:launch-as", {
    appid: _0x789479,
    accountName: _0x3cb95d
  }),
  setSteamAccounts: _0x18efe4 => ipcRenderer.invoke("steam:set-accounts", _0x18efe4),
  getProfile: () => ipcRenderer.invoke("profile:get"),
  notify: _0x45660f => ipcRenderer.invoke("notify:show", _0x45660f),
  loadShop: () => ipcRenderer.invoke("shop:load"),
  shopSearch: _0x692f64 => ipcRenderer.invoke("shop:search", _0x692f64),
  xboxSearch: _0xxs => ipcRenderer.invoke("xbox:search", _0xxs),
  nintendoStorePage: _0xns => ipcRenderer.invoke("nintendo:store-page", _0xns || {}),
  playstationStorePage: _0xps => ipcRenderer.invoke("playstation:store-page", _0xps || {}),
  playstationSearch: _0xpss => ipcRenderer.invoke("playstation:search", _0xpss || {}),
  gameDetails: _0x157feb => ipcRenderer.invoke("game:details", _0x157feb),
  getAchievements: _0x2983ff => ipcRenderer.invoke("steam:achievements", _0x2983ff),
  getSteamFriends: () => ipcRenderer.invoke("steam:friends"),
  getPlayerSummary: _0x566232 => ipcRenderer.invoke("steam:player-summary", _0x566232),
  epicShop: _0x10fa3f => ipcRenderer.invoke("epic:shop", _0x10fa3f || {}),
  gamerpowerFree: () => ipcRenderer.invoke("gamerpower:free"),
  dealsList: () => ipcRenderer.invoke("deals:list"),
  dealsForTitle: arg => ipcRenderer.invoke("deals:forTitle", arg),
  // Preisvergleich ueber alle Stores (CheapShark + optional ITAD, siehe main.js).
  preiseStores: () => ipcRenderer.invoke("preise:stores"),
  preiseVergleich: _0xpvA => ipcRenderer.invoke("preise:vergleich", _0xpvA),
  preiseKandidaten: _0xpkA => ipcRenderer.invoke("preise:kandidaten", _0xpkA),
  preiseVergleichGenau: _0xpgA => ipcRenderer.invoke("preise:vergleichGenau", _0xpgA),
  // ITAD-Shops als Kanaele: Shop-Liste (ohne Key) und Angebote je Shop (mit Key).
  shopShops: () => ipcRenderer.invoke("shop:shops"),
  shopAngebote: _0xsaA => ipcRenderer.invoke("shop:angebote", _0xsaA),
  coverForTitle: arg => ipcRenderer.invoke("cover:forTitle", arg),
  viscodeInfo: () => ipcRenderer.invoke("viscode:info"),
  publisherDetails: _0x1f97b9 => ipcRenderer.invoke("viscode:publisher-details", _0x1f97b9),
  gamePlatforms: _0x21f346 => ipcRenderer.invoke("game:platforms", _0x21f346),
  platformList: () => ipcRenderer.invoke("platforms:list"),
  epicLogin: () => ipcRenderer.invoke("epic:login"),
  epicFriends: () => ipcRenderer.invoke("epic:friends"),
  epicStatus: () => ipcRenderer.invoke("epic:status"),
  epicLogout: () => ipcRenderer.invoke("epic:logout"),
  epicStorePage: _0x499101 => ipcRenderer.invoke("epic:store-page", _0x499101 || {}),
  xboxLogin: () => ipcRenderer.invoke("xbox:login"),
  xboxFriends: () => ipcRenderer.invoke("xbox:friends"),
  xboxProfile: () => ipcRenderer.invoke("xbox:profile"),
  xboxUserProfile: _0x1c96d9 => ipcRenderer.invoke("xbox:user-profile", _0x1c96d9),
  xboxStorePage: _0x503f0b => ipcRenderer.invoke("xbox:store-page", _0x503f0b || {}),
  xboxLibrary: () => ipcRenderer.invoke("xbox:library"),
  xboxBibliothek: () => ipcRenderer.invoke("xbox:bibliothek"),
  xboxGamePass: _0xgp => ipcRenderer.invoke("xbox:gamepass", _0xgp || {}),
  xboxAbo: _0xab => ipcRenderer.invoke("xbox:abo", _0xab || {}),
  xboxAppScan: _0xas => ipcRenderer.invoke("xbox:appScan", _0xas || {}),
  xboxKiStatus: () => ipcRenderer.invoke("xbox:kiStatus"),
  xboxKiModellLaden: () => ipcRenderer.invoke("xbox:kiModellLaden"),
  xboxStatus: () => ipcRenderer.invoke("xbox:status"),
  xboxLogout: () => ipcRenderer.invoke("xbox:logout"),
  epicLauncherLogin: () => ipcRenderer.invoke("epic:launcher-login"),
  epicOwned: () => ipcRenderer.invoke("epic:owned"),
  epicLauncherStatus: () => ipcRenderer.invoke("epic:launcher-status"),
  epicLauncherLogout: () => ipcRenderer.invoke("epic:launcher-logout"),
  gogLogin: () => ipcRenderer.invoke("gog:login"),
  gogStatus: () => ipcRenderer.invoke("gog:status"),
  gogLogout: () => ipcRenderer.invoke("gog:logout"),
  gogOwned: _0xgogO => ipcRenderer.invoke("gog:owned", _0xgogO || {}),
  gogScan: () => ipcRenderer.invoke("gog:scan"),
  ubisoftLogin: () => ipcRenderer.invoke("ubisoft:login"),
  ubisoftStatus: () => ipcRenderer.invoke("ubisoft:status"),
  ubisoftLogout: () => ipcRenderer.invoke("ubisoft:logout"),
  ubisoftScan: () => ipcRenderer.invoke("ubisoft:scan"),
  launcherScan: () => ipcRenderer.invoke("launcher:scan"),
  onLauncherScanLive: _0xslCb => ipcRenderer.on("launcher:scanLive", (_0xslE, _0xslD) => _0xslCb(_0xslD)),
  launcherCrowdDetect: () => ipcRenderer.invoke("launcher:crowdDetect"),
  addLauncherManual: () => ipcRenderer.invoke("launcher:addManual"),
  launcherDeepScan: _0xldsArg => ipcRenderer.invoke("launcher:deepScan", _0xldsArg || {}),
  onLauncherScanProgress: _0xldsCb => ipcRenderer.on("launcher:scanProgress", (_0xldsE, _0xldsD) => _0xldsCb(_0xldsD)),
  authSteam: _0x3d9b91 => ipcRenderer.invoke("auth:steam", _0x3d9b91 || {}),
  authEpic: _0x3c3044 => ipcRenderer.invoke("auth:epic", _0x3c3044 || {}),
  steamRegisterProfile: () => ipcRenderer.invoke("auth:steam-profile"),
  getHwid: () => ipcRenderer.invoke("auth:hwid"),
  checkAccess: () => ipcRenderer.invoke("auth:check-access"),
  getVersion: () => ipcRenderer.invoke("app:version"),
  betaNotice: () => ipcRenderer.invoke("app:beta-notice"),
  serverTime: () => ipcRenderer.invoke("daily:server-time"),
  reportVersion: () => ipcRenderer.invoke("launcher:report-version"),
  setPresence: _0x167fe1 => ipcRenderer.invoke("presence:set", _0x167fe1),
  checkUpdate: () => ipcRenderer.invoke("update:check"),
  launcherStatus: () => ipcRenderer.invoke("launcher:status"),
  runUpdate: _0x3c51a7 => ipcRenderer.invoke("update:run", _0x3c51a7),
  onUpdateProgress: _0x1d5f6d => ipcRenderer.on("update:progress", (_0x3e2c3d, _0x497920) => _0x1d5f6d(_0x497920)),
  syncSteamKeys: () => ipcRenderer.invoke("steam:sync-keys"),
  enrichLibrary: _0x402022 => ipcRenderer.invoke("library:enrich", _0x402022),
  serverGames: () => ipcRenderer.invoke("server:games"),
  login: _0x1a0d17 => ipcRenderer.invoke("auth:login", _0x1a0d17),
  oneclickLogin: _0x4f0737 => ipcRenderer.invoke("auth:oneclick", _0x4f0737),
  oauthLogin: () => ipcRenderer.invoke("auth:oauth"),
  register: _0x487ffc => ipcRenderer.invoke("auth:register", _0x487ffc),
  sendCode: _0xfeadcc => ipcRenderer.invoke("auth:send-code", _0xfeadcc),
  demoLogin: _0xf9b4a3 => ipcRenderer.invoke("auth:demo", {
    username: _0xf9b4a3
  }),
  logout: () => ipcRenderer.invoke("auth:logout"),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  loadSocial: () => ipcRenderer.invoke("social:load"),
  saveSocial: _0x43112e => ipcRenderer.invoke("social:save", _0x43112e),
  socialApi: (_0x4386de, _0x4f9a6b, _0x1df843) => ipcRenderer.invoke("social:api", {
    method: _0x4386de,
    path: _0x4f9a6b,
    body: _0x1df843
  }),
  sendFeedback: _0x255319 => ipcRenderer.invoke("feedback:send", _0x255319),
  getMyFeedback: () => ipcRenderer.invoke("feedback:mine"),
  gameReviews: _0x2dd5d8 => ipcRenderer.invoke("game:reviews", _0x2dd5d8),
  submitGameReview: _0x5815cf => ipcRenderer.invoke("game:review-submit", _0x5815cf),
  deleteGameReview: _0x4ce85b => ipcRenderer.invoke("game:review-delete", _0x4ce85b),
  publisherMine: () => ipcRenderer.invoke("publisher:mine"),
  feedbackPromptDue: () => ipcRenderer.invoke("feedback:prompt-due"),
  familyMine: () => ipcRenderer.invoke("family:mine"),
  familyGet: _0x39fc10 => ipcRenderer.invoke("family:get", _0x39fc10),
  familyCreate: _0x514ab5 => ipcRenderer.invoke("family:create", _0x514ab5 || {}),
  familyJoin: _0x4d200f => ipcRenderer.invoke("family:join", _0x4d200f || {}),
  familyLeave: _0x1c6382 => ipcRenderer.invoke("family:leave", _0x1c6382 || {}),
  familyRename: _0x566051 => ipcRenderer.invoke("family:rename", _0x566051 || {}),
  familyAddMember: _0x3da15e => ipcRenderer.invoke("family:add-member", _0x3da15e || {}),
  familyRemoveMember: _0x245bf6 => ipcRenderer.invoke("family:remove-member", _0x245bf6 || {}),
  familyParental: _0x25cb3e => ipcRenderer.invoke("family:parental", _0x25cb3e || {}),
  familyGameStatus: _0x322629 => ipcRenderer.invoke("family:game-status", _0x322629 || {}),
  copyText: _0x5e1add => ipcRenderer.invoke("clipboard:write", _0x5e1add),
  tenorSearch: _0x22d45e => ipcRenderer.invoke("tenor:search", _0x22d45e),
  mediaDataUrl: _0x294061 => ipcRenderer.invoke("media:data-url", _0x294061),
  bgPickImage: () => ipcRenderer.invoke("bg:pick-image"),
  bgSetWallpaper: pngDataUrl => ipcRenderer.invoke("bg:set-wallpaper", pngDataUrl),
  bgExportFile: arg => ipcRenderer.invoke("bg:export-file", arg),
  bgImportFile: () => ipcRenderer.invoke("bg:import-file"),
  // Teilbare Bibliotheks-Karte: PNG speichern bzw. als Bild in die Zwischenablage.
  karteSpeichern: _0xkspA => ipcRenderer.invoke("karte:speichern", _0xkspA || {}),
  karteKopieren: _0xkkoA => ipcRenderer.invoke("karte:kopieren", _0xkkoA || {}),
  chatPickFile: () => ipcRenderer.invoke("chat:pick-file"),
  chatSaveFile: a => ipcRenderer.invoke("chat:save-file", a),
  onOpenVybg: _0xcb => ipcRenderer.on("bg:open-vybg", (_0xe, _0xd) => _0xcb(_0xd)),
  webappFetchMeta: _0xwaU => ipcRenderer.invoke("webapp:fetch-meta", _0xwaU),
  webappCreate: _0xwaA => ipcRenderer.invoke("webapp:create", _0xwaA),
  webappOpen: _0xwaO => ipcRenderer.invoke("webapp:open", _0xwaO),
  webappList: () => ipcRenderer.invoke("webapp:list"),
  webappLaunch: _0xwaL => ipcRenderer.invoke("webapp:launch", _0xwaL),
  webappCreateShortcut: _0xwaS => ipcRenderer.invoke("webapp:create-shortcut", _0xwaS),
  webappDesktopFromLinks: _0xwaL => ipcRenderer.invoke("webapp:desktop-from-links", _0xwaL),
  webappUninstall: _0xwaX => ipcRenderer.invoke("webapp:uninstall", _0xwaX),
  webappUpdate: _0xwaUp => ipcRenderer.invoke("webapp:update", _0xwaUp),
  // Chromium-eigene Auto-Dunkelfunktion je Ansicht schalten (siehe main.js).
  webAutoDunkel: _0xadA => ipcRenderer.invoke("web:autodunkel", _0xadA || {}),
  autostartStatus: _0xasA => ipcRenderer.invoke("autostart:status", _0xasA),
  autostartSet: _0xasS => ipcRenderer.invoke("autostart:set", _0xasS),
  netReachable: _0xnrA => ipcRenderer.invoke("net:reachable", _0xnrA),
  musicOpen: () => ipcRenderer.invoke("music:open"),
  musicPick: () => ipcRenderer.invoke("music:pick"),
  musicStatus: () => ipcRenderer.invoke("music:status"),
  musicInstall: () => ipcRenderer.invoke("music:install"),
  onMusicProgress: _0xmpCb => ipcRenderer.on("music:progress", (_0xmpE, _0xmpD) => _0xmpCb(_0xmpD)),
  musicPickFolder: () => ipcRenderer.invoke("music:pick-folder"),
  musicListFolder: _0xmlf => ipcRenderer.invoke("music:list-folder", _0xmlf),
  translate: _0x7a11ce => ipcRenderer.invoke("translate:text", _0x7a11ce),
  onDeepLink: _0x4b5a80 => ipcRenderer.on("deep-link", (_0xcfb0fe, _0x4135a9) => _0x4b5a80(_0x4135a9)),
  onForceUpdate: _0x1c0268 => ipcRenderer.on("launcher:force-update", () => _0x1c0268()),
  getPendingDeepLink: () => ipcRenderer.invoke("deeplink:get-pending"),
  launcherLibrary: () => ipcRenderer.invoke("launcher:library"),
  downloadRequest: _0x490d66 => ipcRenderer.invoke("download:request", _0x490d66),
  downloadQueueList: () => ipcRenderer.invoke("download:queue-list"),
  downloadMoveFirst: _0x23b0dd => ipcRenderer.invoke("download:move-first", _0x23b0dd),
  downloadMove: (_0x4de96f, _0x481b80) => ipcRenderer.invoke("download:move", {
    gameId: _0x4de96f,
    dir: _0x481b80
  }),
  downloadCancel: _0xa24b45 => ipcRenderer.invoke("download:cancel", _0xa24b45),
  downloadSetConcurrency: _0x4f11a7 => ipcRenderer.invoke("download:set-concurrency", _0x4f11a7),
  downloadGetConcurrency: () => ipcRenderer.invoke("download:get-concurrency"),
  onDownloadQueue: _0x10ef84 => ipcRenderer.on("download:queue", (_0x5b51b8, _0x49422b) => _0x10ef84(_0x49422b)),
  onDownloadCanceled: _0x37ac1c => ipcRenderer.on("download:canceled", (_0x1c74a5, _0x52a4b2) => _0x37ac1c(_0x52a4b2)),
  vcInstalled: () => ipcRenderer.invoke("vc:installed"),
  vcLaunch: _0xd2f28d => ipcRenderer.invoke("vc:launch", _0xd2f28d),
  vcKill: _0x4b59de => ipcRenderer.invoke("vc:kill", _0x4b59de),
  onGameExited: _0x1ed3a2 => ipcRenderer.on("vc:game-exited", (_0x13a912, _0x58373d) => _0x1ed3a2(_0x58373d)),
  onDownloadProgress: _0xb41a36 => ipcRenderer.on("download:progress", (_0x3b332a, _0x1f6934) => _0xb41a36(_0x1f6934)),
  onGameUpdated: _0x3c0dc5 => ipcRenderer.on("vc:game-updated", (_0x590f41, _0x47317f) => _0x3c0dc5(_0x47317f)),
  downloadLicense: _0x50b3f8 => ipcRenderer.invoke("license:download", _0x50b3f8),
  saveLicense: _0x4ac28a => ipcRenderer.invoke("license:save", _0x4ac28a),
  readLicense: _0x3d536f => ipcRenderer.invoke("license:read", _0x3d536f),
  listLicenses: () => ipcRenderer.invoke("license:list"),
  getBalance: () => ipcRenderer.invoke("wallet:get"),
  changeBalance: _0x1f0080 => ipcRenderer.invoke("wallet:change", _0x1f0080),
  setSettings: _0x464863 => ipcRenderer.invoke("settings:set", _0x464863),
  setWindowGlass: _0xglas => ipcRenderer.invoke("window:setGlass", !!_0xglas),
  setWindowOpacity: _0xwert => ipcRenderer.invoke("window:setOpacity", Number(_0xwert)),
  windowControl: _0xaktion => ipcRenderer.invoke("window:control", String(_0xaktion)),
  onWindowMaximized: _0xcb => {
    const _0xh = (_0xe, _0xmax) => _0xcb(!!_0xmax);
    ipcRenderer.on("window:maximized", _0xh);
    return () => ipcRenderer.removeListener("window:maximized", _0xh);
  },
  onPerfSleep: _0xcb => ipcRenderer.on("perf:sleep", (_0xe, _0xd) => _0xcb(_0xd || {})),
  onPerfWake: _0xcb => ipcRenderer.on("perf:wake", () => _0xcb()),
  perfSlept: () => ipcRenderer.send("perf:slept"),
  perfPlaceholder: () => ipcRenderer.invoke("perf:placeholder"),
  perfPurge: () => ipcRenderer.invoke("perf:purge"),
  gameJoinLobby: _0xgjl => ipcRenderer.invoke("game:join-lobby", _0xgjl),
  launchGame: _0xc38626 => ipcRenderer.invoke("game:launch", _0xc38626),
  launchGameUri: _0xlgu => ipcRenderer.invoke("game:launch", _0xlgu),
  createGameShortcut: _0xcgs => ipcRenderer.invoke("game:createShortcut", _0xcgs),
  createNativeGameShortcut: _0xcngs => ipcRenderer.invoke("game:createNativeShortcut", _0xcngs),
  gameRunning: _0x3a6a50 => ipcRenderer.invoke("game:running", _0x3a6a50),
  killGame: _0x184420 => ipcRenderer.invoke("game:kill", _0x184420),
  installGame: _0x202ee7 => ipcRenderer.invoke("game:install", _0x202ee7),
  uninstallGame: _0x235377 => ipcRenderer.invoke("game:uninstall", _0x235377),
  listDrives: () => ipcRenderer.invoke("disk:list"),
  buyGame: _0x4cdada => ipcRenderer.invoke("game:buy", _0x4cdada),
  openFolder: _0x57ae78 => ipcRenderer.invoke("open:folder", _0x57ae78),
  launcherProzesse: () => ipcRenderer.invoke("launcher:prozesse"),
  launcherAnalyse: _0x4c9a11 => ipcRenderer.invoke("launcher:analyse", _0x4c9a11),
  launcherStarten: _0x4c9a12 => ipcRenderer.invoke("launcher:starten", _0x4c9a12),
  launcherOeffneBibliothek: _0x4c9a12b => ipcRenderer.invoke("launcher:oeffneBibliothek", _0x4c9a12b),
  launcherFreundeScannen: _0x4c9a12c => ipcRenderer.invoke("launcher:freundeScannen", _0x4c9a12c),
  launcherFreundeSync: () => ipcRenderer.invoke("launcher:freundeSync"),
  launcherFreundeCache: () => ipcRenderer.invoke("launcher:freundeCache"),
  onFreundeProgress: _0xcb => {
    const _0xh = (_0xe, _0xd) => _0xcb(_0xd || {});
    ipcRenderer.on("launcher:freundeProgress", _0xh);
    return () => ipcRenderer.removeListener("launcher:freundeProgress", _0xh);
  },
  launcherSpieleScannen: _0x4c9a13 => ipcRenderer.invoke("launcher:spieleScannen", _0x4c9a13),
  launcherOrdnerWaehlen: () => ipcRenderer.invoke("launcher:ordnerWaehlen"),
  gfnListe: () => ipcRenderer.invoke("gfn:liste"),
  onVlScanProgress: _0xvlpCb => ipcRenderer.on("launcher:vlScanProgress", (_0xvlpE, _0xvlpD) => _0xvlpCb(_0xvlpD)),
  startPlatform: _0x58ddab => ipcRenderer.invoke("platform:start", _0x58ddab),
  openExternal: _0x5c1960 => ipcRenderer.invoke("open:external", _0x5c1960),
  openAppBrowser: _0xUrlAb => ipcRenderer.invoke("open:appbrowser", _0xUrlAb),
  geoCountry: () => ipcRenderer.invoke("geo:country"),
  downloadStudio: () => ipcRenderer.invoke("studio:download"),
  exportQuickAccounts: _0x2a1d27 => ipcRenderer.invoke("accounts:export", _0x2a1d27),
  setFullscreen: _0x4c0b74 => ipcRenderer.invoke("window:setFullscreen", _0x4c0b74),
  isFullscreen: () => ipcRenderer.invoke("window:isFullscreen"),
  cloudEscGuard: _0xguard => ipcRenderer.invoke("cloud:esc-guard", _0xguard),
  onFullscreenChanged: _0x339614 => ipcRenderer.on("fullscreen:changed", (_0x2d380e, _0x219d84) => _0x339614(_0x219d84)),
  onGameStatus: _0x12ef49 => ipcRenderer.on("game:status", (_0x5e484b, _0x39e1ce) => _0x12ef49(_0x39e1ce)),
  onGameSendTextRequest: _0xgstr => ipcRenderer.on("game:send-text-request", (_0x5e484c, _0x39e1cf) => _0xgstr(_0x39e1cf)),
  vrStatus: () => ipcRenderer.invoke("vr:status"),
  vrScan: () => ipcRenderer.invoke("vr:scan"),
  vrOpenSteamVR: _0xvrMode => ipcRenderer.invoke("vr:open-steamvr", {
    mode: _0xvrMode
  }),
  vrLaunchGame: _0xvrAppid => ipcRenderer.invoke("vr:launch-game", {
    appid: _0xvrAppid
  }),
  vrPairCode: () => ipcRenderer.invoke("vr:pair-code"),
  vrPairNeu: () => ipcRenderer.invoke("vr:pair-neu"),
  vrGeraete: () => ipcRenderer.invoke("vr:geraete"),
  vrGeraetEntfernen: _0xvrGid => ipcRenderer.invoke("vr:geraet-entfernen", {
    id: _0xvrGid
  }),
  questDetect: () => ipcRenderer.invoke("quest:detect"),
  questInstall: _0xqiArg => ipcRenderer.invoke("quest:install", _0xqiArg || {}),
  questOpenGuide: () => ipcRenderer.invoke("quest:open-guide"),
  onQuestProgress: _0xqpCb => ipcRenderer.on("quest:progress", (_0xqpE, _0xqpD) => _0xqpCb(_0xqpD)),
  openSteamLinkWindow: _0x3d76ae => ipcRenderer.invoke("steam:open-link-window", _0x3d76ae),
  getSteamLinkInfo: () => ipcRenderer.invoke("steam:get-link-info"),
  closeSteamLinkWindow: _0x73f056 => ipcRenderer.invoke("steam:close-link-window", _0x73f056),
  onSteamLinked: _0x598c76 => ipcRenderer.on("steam:linked-success", () => _0x598c76()),
  // Fehler aus der Oberflaeche an den Hauptprozess. send statt invoke: der
  // Renderer soll im Fehlerfall nicht auf eine Antwort warten muessen.
  meldeFehler: _0xuiFehler => ipcRenderer.send("ui:fehler", _0xuiFehler || {})
});